# Generated by Django 3.2.16 on 2024-11-28 00:46

from django.db import migrations, models
import nubien_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('nubien_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/', validators=[nubien_blog.models.validate_image_size]),
        ),
    ]
